package com.example.livingai_lg.ui.models

data class Animal(
    val id: String,
    val name: String? = null,
    val age: Int? = null,
    val breed: String? = null,
    val price: Long? = null,
    val isFairPrice: Boolean? = null,
    val imageUrl: List<String>? = null,
    val location: String? = null,
    val displayLocation: String? = null,
    val distance: Long? = null,
    val views: Long? = null,
    val sellerId: String? = null,
    val sellerName: String? = null,
    val sellerType: String? = null,
    val aiScore: Float? = null,
    val rating: Float? = null,
    val ratingCount: Int? = null,
    val description: String? = null,
    val milkCapacity: Float? = null,
)

val sampleAnimals = listOf(
    Animal(
        id = "1",
        name = "Rita",
        age = 45,
        breed = "Gir",
        location = "Punjab",
        distance = 12000,
        imageUrl = listOf("https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2F4.bp.blogspot.com%2F_tecSnxaePMo%2FTLLVknW8dOI%2FAAAAAAAAACo%2F_kd1ZNBXU1o%2Fs1600%2FGIR%2CGujrat.jpg&f=1&nofb=1&ipt=da6ba1d040c396b64d3f08cc99998f66200dcd6c001e4a56def143ab3d1a87ea","https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcpimg.tistatic.com%2F4478702%2Fb%2F4%2Fgir-cow.jpg&f=1&nofb=1&ipt=19bf391461480585c786d01433d863a383c60048ac2ce063ce91f173e215205d"),
        views = 9001,
        aiScore = 0.80f,
        price = 120000,
        isFairPrice = true,
        rating = 4.7f,
        ratingCount = 2076,
        sellerId = "1",
        sellerName = "Seller 1",
        description = "Premium Gir dairy cow in excellent health condition. High-yielding milk producer with consistent output and gentle temperament, making her ideal for commercial dairy operations or family farms.",
        displayLocation = "Mediatek Pashu Mela, Marathalli, Bangalore (13 km)",
        milkCapacity = 3.2f
    ),
    Animal(
        id = "2",
        name = "Sahi",
        price = 95000,
        age = 35,
        breed = "Sahiwal",
        location = "Punjab",
        isFairPrice = true,
        imageUrl = listOf("https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdnbbsr.s3waas.gov.in%2Fs3a5a61717dddc3501cfdf7a4e22d7dbaa%2Fuploads%2F2020%2F09%2F2020091812-1024x680.jpg&f=1&nofb=1&ipt=bb426406b3747e54151e4812472e203f33922fa3b4e11c4feef9aa59a5733146"),
        distance = 0L,
        views = 100,
        sellerId = "1",
        sellerName = "Seller ???",
        sellerType = "Wholeseller",
        rating = 5f,
        ratingCount = 2076,
        description = "Friendly and energetic companion looking for an active family.",
        milkCapacity = 2.5f
    ),
    Animal(
        id = "3",
        name = "Bessie",
        age = 48,
        breed = "Holstein Friesian",
        location = "Punjab",
        distance = 12000,
        imageUrl = listOf("https://api.builder.io/api/v1/image/assets/TEMP/885e24e34ede6a39f708df13dabc4c1683c3e976?width=786"),
        views = 94,
        aiScore = 0.80f,
        price = 80000,
        isFairPrice = true,
        rating = 4.5f,
        ratingCount = 2076,
        sellerId = "1",
        sellerName = "Seller 1",
        description = "Premium Holstein Friesian dairy cow in excellent health condition. Bessie is a high-yielding milk producer with consistent output and gentle temperament, making her ideal for commercial dairy operations or family farms.",
        displayLocation = "Mediatek Pashu Mela, Marathalli, Bangalore (13 km)",
        milkCapacity = 2.3f
    )
)
